# Generated by Django 5.1.6 on 2025-03-13 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="cover",
            field=models.ImageField(blank=True, null=True, upload_to="book_covers/"),
        ),
        migrations.AddField(
            model_name="book",
            name="sample",
            field=models.FileField(blank=True, null=True, upload_to="book_samples/"),
        ),
    ]
